name: agrismart
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localization: ^0.3.3
  firebase_database: ^12.0.1
  firebase_core: ^4.1.0
  intl: ^0.20.2
  firebase_auth: ^6.1.0
  google_sign_in: ^7.2.0
  flutter_spinkit: ^5.2.2
  url_launcher: ^6.3.2
  fl_chart: ^0.69.0
  syncfusion_flutter_charts: ^31.1.19
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
