// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLedGt-sHiLxwrqLOdGzyQL9sYhqaPL-Q',
    appId: '1:74904330957:web:9131afae23a2b3b3b47f84',
    messagingSenderId: '74904330957',
    projectId: 'agro-smart-dec18',
    authDomain: 'agro-smart-dec18.firebaseapp.com',
    databaseURL: 'https://agro-smart-dec18-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agro-smart-dec18.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNXD_2sZNgJAtF2QqBkWAd-UCmK-Wdwb8',
    appId: '1:74904330957:android:1e0bd454399b9b44b47f84',
    messagingSenderId: '74904330957',
    projectId: 'agro-smart-dec18',
    databaseURL: 'https://agro-smart-dec18-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agro-smart-dec18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAre0ElK_M8iUBV-8XcCINeksZaP9tZ_Bo',
    appId: '1:74904330957:ios:9af96aac9a8d4cd1b47f84',
    messagingSenderId: '74904330957',
    projectId: 'agro-smart-dec18',
    databaseURL: 'https://agro-smart-dec18-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agro-smart-dec18.firebasestorage.app',
    iosBundleId: 'com.example.agrismart',
  );
}
